/**
 * Textos e mensagens da interface do usuário (UX Writing em pt-BR)
 * Centraliza mensagens amigáveis voltadas para estudantes do ensino médio.
 * Sem termos técnicos de infraestrutura ou códigos de erro.
 */

export const MENSAGENS = {
    rotuloTurma: 'Turma:',
    rotuloMatricula: 'Matrícula:',
    criteriosRanking: 'ℹ️ Critérios do ranking: 1º Maior percentual de acerto, 2º Mais acertos absolutos, 3º Menor tempo total, 4º Data de conclusão mais antiga.',
    identificarAntesSimulado: "Por favor, preencha sua identificação (Nome, Turma e Matrícula) antes de iniciar o simulado para registrar sua pontuação no ranking.",
    selecionarAlternativa: "Por favor, selecione uma alternativa antes de confirmar.",
    carregandoBotao: "⏳ Carregando...",
    iniciarSimulado: "Iniciar Simulado →",
    totalGeral: "Total Geral",
    acertos: "Acertos",
    aproveitamento: "Aproveitamento",
    semRespostas: "Nenhuma questão respondida ainda.",
    incentivoPratica: "Continue praticando! Você está no caminho certo.",
    resultadoExcelente: "Excelente resultado! Seu domínio dos conteúdos do ENEM está ótimo!",
    resultadoBom: "Bom desempenho! Revise os tópicos recomendados abaixo para aumentar sua pontuação.",
    prioridadeAlta: "Prioridade alta",
    prioridadeMedia: "Prioridade média",
    prioridadeBaixa: "Prioridade baixa",
    geral: "Geral",
    enem: "ENEM",
    enunciadoIndisponivel: "Enunciado não disponível.",
    imagemQuestao: "Imagem da questão",
    respostaCorreta: "✓ Parabéns, resposta correta!",
    respostaIncorreta: "✕ Resposta incorreta",
    revisarRaciocinio: "Confira o enunciado e a alternativa correta para revisar o raciocínio desta questão.",
    verDiagnostico: "Ver Diagnóstico Completo → ",
    proximaQuestao: "Próxima Questão → ",
    teclaEnter: "Enter ↵",
    rendimentoAlto: "Alto Rendimento",
    revisaoPrioritaria: "Revisão Prioritária",
    rendimentoRegular: "Rendimento Regular",
    revisaoVazia: "Nenhuma questão respondida para revisão.",
    suaResposta: "Sua resposta: ",
    gabaritoOficial: "Gabarito Oficial: ",
    correta: "(Correta)",
    incorreta: "(Incorreta)",
    explicacaoPedagogica: "💡 Explicação Pedagógica: ",
    todasTurmas: "Todas as Turmas (Ranking Geral)",
    anonimo: "Anônimo",
    voce: "Você",
    tituloPagina: "Performance Quest — Rendimento por Assunto (ENEM)",
    nomeProjeto: "Performance Quest",
    subtituloProjeto: "Simulados e recomendações de estudo para o ENEM",
    tituloCadastro: "👤 Identificação do Estudante",
    nomeAluno: "Nome do Aluno",
    orientacaoCadastro: "Preencha seus dados para salvar suas tentativas e participar do ranking da sua turma:",
    campoNome: "Nome Completo: *",
    campoTurma: "Turma: *",
    campoMatricula: "Matrícula / ID: *",
    tituloConfiguracao: "🚀 Configuração do Simulado",
    orientacaoSimulado: "Prepare-se com questões oficiais do ENEM e receba o diagnóstico de estudo com os 3 assuntos prioritários que você mais precisa focar.",
    campoArea: "Área do Conhecimento:",
    todasAreas: "Todas as Áreas (Simulado Geral)",
    areaMatematica: "Matemática e suas Tecnologias",
    areaNatureza: "Ciências da Natureza (Física, Química, Biologia)",
    areaHumanas: "Ciências Humanas (História, Geografia, Filosofia)",
    areaLinguagens: "Linguagens, Códigos e suas Tecnologias",
    campoAno: "Ano das Questões:",
    todosAnos: "2022 e 2023 (misturado)",
    ano2022: "ENEM 2022",
    ano2023: "ENEM 2023",
    campoQuantidade: "Quantidade de Questões:",
    quantidadeRapida: "5 questões (Diagnóstico Rápido)",
    quantidadeRecomendada: "10 questões (Recomendado)",
    quantidadeCompleta: "15 questões (Completo)",
    tituloComoFunciona: "ℹ️ Como funciona o diagnóstico e o Ranking?",
    comoFunciona: "A cada simulado, analisamos seus erros e o tempo de resposta para indicar os assuntos que você mais precisa estudar. Sua pontuação também entra no Ranking da sua Turma (critérios: maior aproveitamento, mais acertos e menor tempo).",
    tituloResultado: "📊 Resultado do Simulado",
    carregandoDiagnostico: "Carregando diagnóstico...",
    tituloPrioridades: "Seus 3 Assuntos Prioritários de Estudo",
    orientacaoPrioridades: "Com base nas questões que você errou e no tempo que levou para responder.",
    tituloDesempenhoArea: "Desempenho por Área de Conhecimento",
    tituloRevisao: "📝 Revisão Detalhada do Gabarito",
    orientacaoRevisao: "Confira abaixo cada questão respondida nesta sessão, a alternativa marcada, o gabarito oficial e a explicação pedagógica.",
    tituloRanking: "🏆 Ranking dos Estudantes",
    campoFiltroTurma: "Filtrar por Turma:",
    filtroTodasTurmas: "Todas as Turmas (Geral)",
    carregandoClassificacao: "Carregando classificação...",
    tituloCriteriosRanking: "Critérios do ranking:",
    tituloEditarCadastro: "👤 Meus Dados de Identificação",
    campoMatriculaEdicao: "Matrícula: *",
    tituloHistorico: "📈 Meu Histórico",
    rodapeProjeto: "Performance Quest: Rendimento por Assunto © 2026 — UNINORTE / Manaus-AM",
    rodapeDisciplina: "Atividades Práticas Interdisciplinares de Extensão II",
    aluno: "Aluno",
    botaoRanking: "🏆 Ranking",
    exemploTurma: "3A",
    botaoAlterarDados: "✏️ Alterar Dados",
    botaoSalvarCadastro: "Salvar Identificação",
    botaoVerRanking: "🏆 Ver Ranking",
    botaoHistorico: "Meu Histórico",
    area: "Área",
    assunto: "Assunto",
    contadorInicial: "Questão 1 de 5",
    resumoTentativa: "Resumo da Tentativa",
    botaoNovoSimulado: "Fazer Novo Simulado",
    botaoRankingTurma: "🏆 Ver Ranking da Turma",
    botaoAtualizar: "🔄 Atualizar",
    botaoCancelar: "Cancelar",
    botaoSalvarAlteracoes: "Salvar Alterações",
    botaoLimparHistorico: "Limpar Histórico",
    botaoFechar: "Fechar",
    botaoConfirmarResposta: "Confirmar Resposta",
    botaoProximaQuestao: "Próxima Questão →",
    tituloAlterarDados: "Alterar meus dados",
    tituloVerRanking: "Ver Ranking da Turma",
    exemploNome: "Ex: André Luiz",
    exemplosTurmas: "Ex: 3A, 3B, 3º Ano 1",
    exemploMatricula: "Ex: 202601",
    questoes: "Questões",
    tempoTotal: "Tempo Total",
    colunasRanking: ["#", "Estudante", "Turma", "Acertos", "Aproveitamento", "Tempo Total"],
    contadorQuestao: (indice, total) => `Questão ${indice} de ${total}`,
    imagemAlternativa: letra => `Imagem da alternativa ${letra}`,
    teclaAlternativa: letra => `Tecla ${letra}`,
    gabarito: letra => `Gabarito oficial: Alternativa ${letra}.`,
    metricasAssunto: item => `Taxa de acerto: ${item.taxaAcerto.toFixed(0)}% (${item.acertos}/${item.total} acertos) • Tempo médio: ${Math.round(item.tempoMedio)}s/questão`,
    resumoAcertos: (acertos, total) => `${acertos}/${total} Acertos`,
    questaoNumero: numero => `Questão ${numero}`,
    anoEnem: ano => `ENEM ${ano}`,
    statusResposta: (acertou, tempo) => `${acertou ? "✓ Acertou" : "✕ Errou"} (${tempo}s)`,
    alternativa: letra => `Alternativa ${letra}`,
    turma: turma => `Turma ${turma}`,
    prioridadeHistorico: (item, prioridade) => ` — Taxa de acerto: ${item.taxaAcerto.toFixed(0)}% • ${prioridade}`,

    // Carregamento
    carregandoQuestoes: 'Carregando questões...',
    carregandoRanking: 'Carregando ranking...',
    carregandoGeral: 'Carregando...',

    // Erros amigáveis
    erroCarregarQuestoes: 'Não conseguimos carregar as questões agora. Tente novamente em instantes.',
    erroCarregarRanking: 'Não foi possível carregar o ranking agora. Tente novamente em instantes.',
    erroRegistrarResposta: 'Não foi possível registrar sua resposta. Tente novamente.',
    erroGenericoTitulo: '⚠️ Algo não saiu como esperado',
    erroGenericoDesc: 'Não conseguimos carregar o conteúdo agora. Tente novamente em instantes.',
    botaoTentarNovamente: '🔄 Tentar novamente',
    imagemIndisponivel: 'Não conseguimos carregar esta imagem. ',

    // Feedback de salvamento no ranking
    salvandoPontuacao: 'Salvando sua pontuação no ranking...',
    pontuacaoSalva: (turma) => turma ? `Pontuação registrada com sucesso no ranking da Turma ${turma}!` : 'Pontuação registrada com sucesso no ranking da turma!',
    pontuacaoPendente: 'Não conseguimos salvar no ranking agora, mas sua pontuação está guardada. Vamos tentar de novo automaticamente.',
    pontuacaoNaoGuardada: 'Não conseguimos guardar sua pontuação neste aparelho nem salvar no ranking agora. Mantenha esta tela aberta e tente novamente.',

    // Diagnóstico e Recomendações
    semQuestoesRecomendacao: 'Responda pelo menos 2 questões do mesmo assunto para receber recomendações de estudo.',
    dicaEstudo: '💡 Dica de estudo: Dedique seus próximos momentos de revisão para reforçar a teoria e resolver mais exercícios desse assunto.',
    assuntosRecomendadosTitulo: 'Assuntos recomendados para estudo:',
    desempenhoPorAssunto: 'Desempenho por Assunto',
    aindaSemRespostas: 'Ainda sem respostas',

    // Histórico e Ranking
    confirmarLimparHistorico: 'Tem certeza de que deseja limpar seu histórico de simulados salvos neste aparelho?',
    historicoVazio: 'Nenhuma questão respondida ainda no seu histórico.',
    rankingVazio: 'Nenhum resultado registrado para esta turma ainda. Seja o primeiro a completar o simulado!',

    // Cadastro de estudante
    cadastroNaoConfirmado: 'Não foi possível confirmar seu cadastro para salvar no ranking agora. Atualize seus dados e tente novamente.',
    nomeJaCadastrado: 'Já existe um cadastro com esse nome. Confira seu nome completo e tente novamente.',
    erroSalvarCadastro: 'Não foi possível salvar seus dados no momento. Tente novamente.'
};
